-- ==========================================
-- BARAGEM POS - SUPABASE SCHEMA MIGRATION
-- ==========================================

-- 1. Create Categories Table
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

-- 2. Create Customers Table
CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    nickname TEXT,
    birthday DATE,
    document TEXT UNIQUE, -- CPF or RG
    phone TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Products Table
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    cost_price DECIMAL(10,2) DEFAULT 0,
    stock DECIMAL(10,3) DEFAULT 0, -- DECIMAL for fractional units
    unit TEXT DEFAULT 'un',
    purchase_unit TEXT,
    unit_conversion_factor DECIMAL(10,3) DEFAULT 1,
    image_url TEXT,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    active BOOLEAN DEFAULT true,
    type TEXT DEFAULT 'simple', -- simple, variable, composition
    parent_id BIGINT REFERENCES products(id) ON DELETE SET NULL
);

-- 4. Create Product Ingredients Table
CREATE TABLE product_ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE NOT NULL,
    ingredient_id BIGINT REFERENCES products(id) ON DELETE RESTRICT NOT NULL,
    quantity DECIMAL(10,3) NOT NULL
);

-- 5. Create Orders Table
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pulseira TEXT NOT NULL,
    customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
    customer_name TEXT,
    customer_phone TEXT,
    status TEXT DEFAULT 'open', -- open, paid, closed
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    closed_at TIMESTAMP WITH TIME ZONE
);

-- 6. Create Order Items Table
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE RESTRICT,
    quantity DECIMAL(10,3) DEFAULT 1,
    price_at_time DECIMAL(10,2) NOT NULL,
    cost_at_time DECIMAL(10,2) DEFAULT 0
);

-- 7. Create Transactions Table
CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    amount DECIMAL(10,2) NOT NULL,
    method TEXT NOT NULL, -- cash, card, pix
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Create Settings Table
CREATE TABLE settings (
    key TEXT PRIMARY KEY,
    value TEXT
);

-- 9. Create Cashier Sessions Table
CREATE TABLE cashier_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opened_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    closed_at TIMESTAMP WITH TIME ZONE,
    initial_balance DECIMAL(10,2) DEFAULT 0,
    final_balance DECIMAL(10,2),
    total_cash_sales DECIMAL(10,2),
    amortization DECIMAL(10,2) DEFAULT 0,
    status TEXT DEFAULT 'open'
);

-- ==========================================
-- FUNCTIONS AND TRIGGERS (STOCK MANAGEMENT)
-- ==========================================

-- Function to deduct stock safely during order item insertion
CREATE OR REPLACE FUNCTION deduct_stock_on_order() 
RETURNS TRIGGER AS $$
DECLARE
    prod_type TEXT;
    ing_record RECORD;
BEGIN
    -- Obter o tipo do produto
    SELECT type INTO prod_type FROM products WHERE id = NEW.product_id;

    IF prod_type = 'simple' THEN
        -- Produto Simples
        UPDATE products 
        SET stock = stock - NEW.quantity 
        WHERE id = NEW.product_id;
        
    ELSIF prod_type = 'composition' THEN
        -- Produto Composto: Abater estoque dos ingredientes base
        FOR ing_record IN (SELECT ingredient_id, quantity FROM product_ingredients WHERE product_id = NEW.product_id)
        LOOP
            UPDATE products 
            SET stock = stock - (ing_record.quantity * NEW.quantity) 
            WHERE id = ing_record.ingredient_id;
        END LOOP;
        
    ELSIF prod_type = 'variable' THEN
        -- Valid layer: Frontend must send the exact variation
        RAISE EXCEPTION 'Cannot add a variable parent product directly. Use its variation.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to fire the stock deduction BEFORE/AFTER inserting an order item
CREATE TRIGGER trigger_deduct_stock_on_order
AFTER INSERT ON order_items
FOR EACH ROW
EXECUTE FUNCTION deduct_stock_on_order();

-- Function to restore stock when deleting an order item (cancellation)
CREATE OR REPLACE FUNCTION restore_stock_on_cancel() 
RETURNS TRIGGER AS $$
DECLARE
    prod_type TEXT;
    ing_record RECORD;
BEGIN
    SELECT type INTO prod_type FROM products WHERE id = OLD.product_id;

    IF prod_type = 'simple' THEN
        UPDATE products 
        SET stock = stock + OLD.quantity 
        WHERE id = OLD.product_id;
        
    ELSIF prod_type = 'composition' THEN
        FOR ing_record IN (SELECT ingredient_id, quantity FROM product_ingredients WHERE product_id = OLD.product_id)
        LOOP
            UPDATE products 
            SET stock = stock + (ing_record.quantity * OLD.quantity) 
            WHERE id = ing_record.ingredient_id;
        END LOOP;
    END IF;

    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

-- Trigger to restore stock
CREATE TRIGGER trigger_restore_stock_on_cancel
AFTER DELETE ON order_items
FOR EACH ROW
EXECUTE FUNCTION restore_stock_on_cancel();

-- ==========================================
-- SEED INITIAL DATA (OPTIONAL)
-- ==========================================
INSERT INTO categories (name) VALUES ('Bebidas'), ('Drinks'), ('Comidas') ON CONFLICT DO NOTHING;

INSERT INTO products (name, price, stock, category_id, type)
VALUES 
    ('Cerveja Lata', 8.00, 120, (SELECT id FROM categories WHERE name = 'Bebidas'), 'simple'),
    ('Cerveja 600ml', 14.00, 60, (SELECT id FROM categories WHERE name = 'Bebidas'), 'simple'),
    ('Dose Vodka', 12.00, 40, (SELECT id FROM categories WHERE name = 'Drinks'), 'simple'),
    ('Espetinho', 10.00, 50, (SELECT id FROM categories WHERE name = 'Comidas'), 'simple')
ON CONFLICT DO NOTHING;
