-- TABLE: suppliers
CREATE TABLE IF NOT EXISTS suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    document TEXT,
    phone TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- TABLE: purchase_orders
CREATE TABLE IF NOT EXISTS purchase_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
    invoice_number TEXT,
    total_amount DECIMAL(10,2) DEFAULT 0,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'reconciled')), 
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    reconciled_at TIMESTAMP WITH TIME ZONE
);

-- TABLE: purchase_order_items
CREATE TABLE IF NOT EXISTS purchase_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT REFERENCES purchase_orders(id) ON DELETE CASCADE,
    
    -- Raw data entered by buyer
    raw_name TEXT NOT NULL,
    raw_quantity DECIMAL(10,3) NOT NULL,
    raw_unit_price DECIMAL(10,2) NOT NULL,
    
    -- Reconciliation data entered by manager
    product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
    reconciled_quantity DECIMAL(10,3), -- How many units in the system this represents
    reconciled_unit_cost DECIMAL(10,2) -- The unit cost calculated after reconciliation
);
